import type {
  ActivityClock,
  Approach,
  PressureObject,
  StateObject,
  SupportMode,
} from '../domain/types';

export const telefonAversjon: StateObject = {
  id: 'telefon_aversjon',
  conditionLabel: 'Terskel',
  objectLabel: 'telefonrøret på bordet',
  label: 'Terskel ved telefonen',
  anchor: 'phone',
  visibleSigns: [
    'røret ligger for synlig på bordet',
    'første setning er skrevet, men ikke brukt',
    'stolen står akkurat litt for langt unna',
  ],
  consequences: {
    threatens: 'gjør sosial risiko større enn selve samtalen',
    worsens: 'utsetter første berøring og trekker Elling mot forklaring i stedet for øving',
    softens: 'manus, varslet vindu og Gretes nummer innen rekkevidde',
    transformsInto: 'tålt nærvær ved telefonbordet',
  },
  description:
    'Telefonen er ikke bare et apparat. Den er overgang, improvisasjon og risiko for å bli tatt på senga.',
  pressure: 0.72,
};

export const phoneApproaches: Approach[] = [
  {
    id: 'none',
    label: 'Bare prøv',
    description: 'Frank ber Elling øve uten ekstra ramme.',
    trustDelta: -0.04,
    controlDelta: -0.08,
    pressureDelta: 0.12,
  },
  {
    id: 'written_script',
    label: 'Skriftlig manus',
    description: 'Elling får nøyaktig første setning og en utgangsreplikk.',
    trustDelta: 0.03,
    controlDelta: 0.18,
    pressureDelta: -0.08,
  },
  {
    id: 'pre_agreed_window',
    label: 'Avtalt tidsvindu',
    description: 'Telefonøving skjer i et lite, varslet vindu.',
    trustDelta: 0.02,
    controlDelta: 0.14,
    pressureDelta: -0.05,
  },
  {
    id: 'tolerate_ringtone',
    label: 'Bare tåle ringelyden',
    description: 'Målet er ikke å svare. Bare bli i rommet mens telefonen ringer.',
    trustDelta: 0.04,
    controlDelta: 0.22,
    pressureDelta: -0.16,
  },
  {
    id: 'grete_primes_first',
    label: 'Grete forbereder først',
    description: 'Grete gjør rammen sosialt tryggere før Frank ber om øving.',
    trustDelta: 0.05,
    controlDelta: 0.1,
    pressureDelta: -0.12,
  },
  {
    id: 'frank_pushes',
    label: 'Frank presser tydelig',
    description: 'Frank gjør framdrift viktigere enn Ellings opplevelse av kontroll.',
    trustDelta: -0.09,
    controlDelta: -0.18,
    pressureDelta: 0.2,
  },
];

export function getApproach(id: string): Approach {
  const approach = phoneApproaches.find((item) => item.id === id);
  if (!approach) throw new Error(`Unknown approach: ${id}`);
  return approach;
}

export const phonePressureObjects: PressureObject[] = [
  {
    id: 'restlessness',
    conditionLabel: 'Rastløshet',
    objectLabel: 'lesestolen som aldri blir sittet i',
    label: 'Rastløshet',
    anchor: 'chair',
    visibleSigns: [
      'puten ligger vridd',
      'boken er åpen på samme side',
      'kaffekoppen står halvtom ved stolbeinet',
    ],
    consequences: {
      threatens: 'gjør venting og varslede telefonvinduer sprø',
      worsens: 'nattlig rydding og avbrutte rutiner',
      softens: 'kort tur, lavterskelkontakt, en aktivitet som ikke ber om forklaring',
      transformsInto: 'bevegelse som kan bære første steg',
    },
    escalatesInto: 'uro, brudd, nattlig rydding',
    softenedBy: 'kort tur, lavterskelkontakt, en aktivitet som ikke ber om forklaring',
    designPurpose: 'Turns stagnation into visible pressure attached to a routine object.',
    clock: 0.45,
  },
  {
    id: 'shame',
    conditionLabel: 'Skam',
    objectLabel: 'avvist manusark under sofaputen',
    label: 'Skam',
    anchor: 'sofa',
    visibleSigns: [
      'arket er brettet med teksten inn',
      'Frank sitt navn er strøket over',
      'sofaen er valgt fremfor telefonbordet',
    ],
    consequences: {
      threatens: 'gjør hjelp lett å lese som inspeksjon',
      worsens: 'unngåelse, mistillit og tapte avtaler',
      softens: 'verdighet, liten seier, oppfølging uten dom',
      transformsInto: 'en replikk Elling kan eie selv',
    },
    escalatesInto: 'unngåelse, mistillit, tapt avtale',
    softenedBy: 'verdighet, liten seier, oppfølging uten dom',
    designPurpose: 'Makes failure socially meaningful, not merely numeric.',
    clock: 0.58,
  },
  {
    id: 'sleep_debt',
    conditionLabel: 'Tåke',
    objectLabel: 'soveromsdøren med lysstripe under',
    label: 'Tåke',
    anchor: 'bedroom',
    visibleSigns: [
      'dynen ligger urørt men krøllet',
      'lyset sto på for lenge',
      'morgenkoppen er ikke funnet fram',
    ],
    consequences: {
      threatens: 'låser formiddagens øving bak lavt overskudd',
      worsens: 'kort lunte, avlyst formiddag og dør som lukker seg',
      softens: 'rutine, mindre krav, kveld som ikke rakner',
      transformsInto: 'rolig start med færre valg',
    },
    escalatesInto: 'lavt overskudd, irritabilitet, avlyst formiddag',
    softenedBy: 'rutine, mindre krav, kveld som ikke rakner',
    designPurpose: 'Creates practical constraint before moral judgment.',
    clock: 0.35,
  },
  {
    id: 'unpaid_bill',
    conditionLabel: 'Forpliktelse',
    objectLabel: 'uåpnet regning under avisen',
    label: 'Forpliktelse',
    anchor: 'desk',
    visibleSigns: [
      'konvolutten har NAV-logo',
      'avisen dekker fristen men ikke hjørnet',
      'pennen ligger klar uten å ha skrevet noe',
    ],
    consequences: {
      threatens: 'trekker telefonøving mot byråkratisk krise',
      worsens: 'bortforklaring, hastverk og Frank som saksbehandler',
      attracts: 'praktisk hjelp og NAV-linje',
      softens: 'telefon til NAV, budsjettstøtte, Frank som holder linjen åpen',
    },
    escalatesInto: 'stresspigg, bortforklaring, krise',
    softenedBy: 'telefon til NAV, budsjettstøtte, Frank som holder linjen åpen',
    designPurpose: 'Makes bureaucracy concrete and timed while preserving the abstract pressure.',
    clock: 0.72,
  },
  {
    id: 'hope',
    conditionLabel: 'Lettelse',
    objectLabel: 'telefonlappen med Gretes nummer',
    label: 'Lettelse',
    anchor: 'phone',
    visibleSigns: [
      'nummeret er skrevet to ganger',
      'første setning står ferdig',
      'lappen ligger nær røret, ikke i skuffen',
    ],
    consequences: {
      threatens: 'kan bli resignasjon hvis den står alene',
      attracts: 'mild kontakt, humor og synlig framgang',
      softens: 'liten suksess, tilhørighet, synlig fremgang',
      transformsInto: 'mot til ett avgrenset ringevindu',
    },
    escalatesInto: 'resignasjon hvis den blir stående alene',
    softenedBy: 'liten suksess, tilhørighet, synlig fremgang',
    designPurpose: 'Lets positive states be fragile too and ties them to an object.',
    clock: 0.28,
  },
  {
    id: 'phone_fear',
    conditionLabel: 'Terskel',
    objectLabel: 'telefonrøret som ligger for synlig',
    label: 'Terskel',
    anchor: 'phone',
    visibleSigns: [
      'røret er tørket rent',
      'stolen er skjøvet akkurat utenfor rekkevidde',
      'blikket går til telefonen før samtalen starter',
    ],
    consequences: {
      threatens: 'blokkerer første berøring og gjør ringelyden større enn oppgaven',
      worsens: 'retrett, prinsipper og hender som blir opptatt med ingenting',
      softens: 'manus, ringelyd uten svarplikt, Grete som varsler først',
      transformsInto: 'tålt nærvær ved telefonbordet',
    },
    escalatesInto: 'retrett, pompøs forsvarstale, urørt telefon',
    softenedBy: 'manus, ringelyd uten svarplikt, Grete som varsler først',
    designPurpose: 'Keeps the phone pressure concrete without naming Elling as the problem.',
    clock: 0.66,
  },
  {
    id: 'dignity_exposure',
    conditionLabel: 'Blottstillelse',
    objectLabel: 'Franks stol vendt mot forsøket',
    label: 'Blottstillelse',
    anchor: 'sofa',
    visibleSigns: [
      'stolen står som et publikum',
      'Frank noterer mer enn han trøster',
      'Elling retter på jakken før han nærmer seg røret',
    ],
    consequences: {
      threatens: 'forvandler øving til kompetanseprøve',
      worsens: 'sinne mot Frank og forsvarstaler om rimelighet',
      softens: 'avstand, fraværende oppsett, humor som gir ansiktet tilbake',
      transformsInto: 'verdighet bevart gjennom sideveis latter',
    },
    escalatesInto: 'sinne, mistillit, øving som offentlig eksamen',
    softenedBy: 'avstand, fraværende oppsett, humor som gir ansiktet tilbake',
    designPurpose: 'Separates observed exposure from any claim about inner pathology.',
    clock: 0.52,
  },
];

export const phoneSupportModes: SupportMode[] = [
  {
    id: 'routine',
    label: 'Rutine',
    good: 'varslede tider, samme stol, samme første steg',
    risk: 'kan bli en penere form for stillstand',
    covers: ['sleep_debt', 'phone_fear', 'restlessness'],
    weak: ['unpaid_bill', 'hope', 'dignity_exposure'],
  },
  {
    id: 'gentle_contact',
    label: 'Lav kontakt',
    good: 'Frank holder avstand og lar rommet svare først',
    risk: 'kan bli høflig venting mens regningen modner',
    covers: ['shame', 'dignity_exposure', 'hope'],
    weak: ['unpaid_bill', 'restlessness', 'phone_fear'],
  },
  {
    id: 'practical_help',
    label: 'Praktisk hjelp',
    good: 'manus, nummer, NAV-linje, en fysisk ting å holde i',
    risk: 'kan se ut som inspeksjon forkledd som omsorg',
    covers: ['unpaid_bill', 'phone_fear', 'sleep_debt'],
    weak: ['shame', 'dignity_exposure', 'hope'],
  },
  {
    id: 'challenge',
    label: 'Lite press',
    good: 'en ekte øving, ikke enda en samtale om øving',
    risk: 'farlig når overskuddet allerede ligger på gulvet',
    covers: ['restlessness', 'hope', 'phone_fear'],
    weak: ['sleep_debt', 'shame', 'dignity_exposure'],
  },
  {
    id: 'boundary',
    label: 'Grense',
    good: 'beskytter rommet mot Grete, NAV og velmenende stormvær',
    risk: 'kan bevare isolasjon litt for effektivt',
    covers: ['dignity_exposure', 'shame', 'sleep_debt'],
    weak: ['restlessness', 'unpaid_bill', 'hope'],
  },
  {
    id: 'disclosure',
    label: 'Navngi det',
    good: 'sier den vanskelige tingen uten å lage teater av den',
    risk: 'for tidlig intimitet kan lukke døren',
    covers: ['shame', 'hope', 'dignity_exposure'],
    weak: ['phone_fear', 'unpaid_bill', 'sleep_debt'],
  },
  {
    id: 'humor_play',
    label: 'Sideveis humor',
    good: 'lar Elling beholde verdighet ved å latterliggjøre øvelsen',
    risk: 'kan bli for lett når brevet faktisk har frist',
    covers: ['phone_fear', 'shame', 'restlessness'],
    weak: ['unpaid_bill', 'sleep_debt', 'dignity_exposure'],
  },
];

export const phoneActivityClocks: ActivityClock[] = [
  {
    id: 'ringtone',
    label: 'Tåle ringelyden',
    description: 'Bli i stuen mens telefonen får lov til å være telefon.',
    segments: 6,
    filled: 2,
    diceSlots: ['safe', 'risky', 'empty'],
  },
  {
    id: 'scripted_sentence',
    label: 'Første setning',
    description: 'Si én innøvd åpning før samtalen blir et land uten kart.',
    segments: 8,
    filled: 2,
    diceSlots: ['safe', 'empty', 'locked'],
  },
  {
    id: 'grete_call',
    label: 'Ringe Grete',
    description: 'En kjent stemme, men ikke nødvendigvis en liten stemme.',
    segments: 8,
    filled: 1,
    diceSlots: ['risky', 'empty', 'locked'],
  },
];
